/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apresentacao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;
import negocio.Movimentacao;
import utilitario.EstacionamentoUtil;

/**
 *
 * @author gabri
 */
public class TelaResultadoRelatorio extends javax.swing.JFrame implements ActionListener{
    private JFrame parent;
    /**
     * Creates new form TelaResultadoRelatorio
     */
    public TelaResultadoRelatorio(TelaInicialRelatorio telaInicial, List<Movimentacao> movimentacoes, LocalDateTime data) {
        this.parent = telaInicial;
        initComponents();
        setLocationRelativeTo(null);
        
        String textoFaturamento = EstacionamentoUtil.gerarTextoFaturamento(data, movimentacoes) ;
        lblTextoFaturamento.setText(textoFaturamento);
        
        Object[][] conteudoFaturamento = preencherTabela(movimentacoes);
        tblFaturamento.setModel(
        new DefaultTableModel(
        conteudoFaturamento,
        new String[] {
            "Placa", "Entrada", "Saída", "Valor"
        }));
        
        btnOK.addActionListener(this);
        btnOK.setActionCommand("ok");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblTextoFaturamento = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFaturamento = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Relatório");
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setPreferredSize(new java.awt.Dimension(540, 60));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnOK.setText("OK");
        jPanel2.add(btnOK, new java.awt.GridBagConstraints());

        jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel4.setPreferredSize(new java.awt.Dimension(540, 60));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        lblTextoFaturamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTextoFaturamento.setText("[faturamento]");
        jPanel4.add(lblTextoFaturamento, new java.awt.GridBagConstraints());

        jPanel3.add(jPanel4, java.awt.BorderLayout.SOUTH);

        tblFaturamento.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Valor", "Entrada", "Saída", "Placa"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblFaturamento);

        jPanel3.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTextoFaturamento;
    private javax.swing.JTable tblFaturamento;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        parent.setVisible(true);
        this.dispose();
    }

    private Object[][] preencherTabela(List<Movimentacao> movimentacoes) {
        Object[][] conteudo = new Object[movimentacoes.size()][4];
        
        for (int i = 0; i < movimentacoes.size(); i++){
            conteudo[i][0] = movimentacoes.get(i).getVeiculo().getPlaca();
            conteudo[i][1] = EstacionamentoUtil.getDisplayData(movimentacoes.get(i).getEntrada());
            conteudo[i][2] = EstacionamentoUtil.getDisplayData(movimentacoes.get(i).getSaida());
            conteudo[i][3] = movimentacoes.get(i).getValor();
        }
        return conteudo;
    }
}
