/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apresentacao;

import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author gabri
 */
public class TelaInicialMovimentacao extends javax.swing.JFrame implements ActionListener{


    /**
     * Creates new form TelaInicialMovimentacao
     */
    public TelaInicialMovimentacao() {
        initComponents();
        setSize(new Dimension(450, 300));
        setLocationRelativeTo(null);
        btnEntrar.addActionListener(this);
        btnEntrar.setActionCommand("entrar");
        btnSair.addActionListener(this);
        btnSair.setActionCommand("sair");

    }
    
    @Override
    public void actionPerformed(ActionEvent e) {
        JFrame tela = null;
        if (e.getActionCommand().equals("entrar")){
            tela = new TelaEntradaVeiculo(this);
        }
        else if (e.getActionCommand().equals("sair")){
            tela = new TelaSaidaVeiculo(this);
        }
        
        tela.setVisible(true);
        this.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnEntrar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema Estacionamento");
        setPreferredSize(new java.awt.Dimension(400, 200));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(400, 200));
        jPanel1.setLayout(new java.awt.GridLayout(1, 2));

        btnEntrar.setText("Entrada de Veículo");
        jPanel1.add(btnEntrar);

        btnSair.setText("Saída de Veículo");
        jPanel1.add(btnSair);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
