/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apresentacao;

import controle.EstacionamentoController;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDateTime;
import java.util.List;
import negocio.Movimentacao;

/**
 *
 * @author gabri
 */
public class TelaInicialRelatorio extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form TelaInicialRelatorio
     */
    public TelaInicialRelatorio() {
        initComponents();
        setLocationRelativeTo(null);
        
        btnGerar.addActionListener(this);
        btnGerar.setActionCommand("gerar");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblAno = new javax.swing.JLabel();
        cboAno = new javax.swing.JComboBox<>();
        lblMes = new javax.swing.JLabel();
        cboMes = new javax.swing.JComboBox<>();
        btnGerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerar Relatório");
        setMaximumSize(new java.awt.Dimension(600, 150));
        setMinimumSize(new java.awt.Dimension(600, 150));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(600, 150));
        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 5, 40));

        lblAno.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblAno.setText("Ano:");
        jPanel1.add(lblAno);

        cboAno.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cboAno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2024", "2023", "2022", "2021" }));
        jPanel1.add(cboAno);

        lblMes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMes.setText("Mês:");
        jPanel1.add(lblMes);

        cboMes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jPanel1.add(cboMes);

        btnGerar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnGerar.setText("Gerar");
        jPanel1.add(btnGerar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JComboBox<String> cboAno;
    private javax.swing.JComboBox<String> cboMes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAno;
    private javax.swing.JLabel lblMes;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        // recupera ano e mês escolhidos
        int ano = Integer.parseInt((String) cboAno.getSelectedItem());
        int mes = (Integer)cboMes.getSelectedIndex() + 1;
        // buscar movimentações conforme período
        EstacionamentoController controller = new EstacionamentoController();
        LocalDateTime data = LocalDateTime.of(ano, mes, 1, 0, 0);
        List<Movimentacao> movimentacoes = controller.emitirRelatorio(data);
        // exibe tela de conteúdo e faturamento
        TelaResultadoRelatorio telaRelatorio = new TelaResultadoRelatorio(this, movimentacoes, data); 
        
        telaRelatorio.setVisible(true);
        this.dispose();
    }
}
