/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apresentacao;

import controle.EstacionamentoController;
import controle.EstacionamentoException;
import controle.VeiculoException;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import negocio.Movimentacao;

/**
 *
 * @author gabri
 */
public class TelaSaidaVeiculo extends javax.swing.JFrame implements ActionListener{
    private JFrame parent;
    
    /**
     * Creates new form TelaSaidaVeiculo
     */
    public TelaSaidaVeiculo(JFrame parent) {
        this.parent = parent;
        initComponents();
        setSize(new Dimension(400, 200));
        setLocationRelativeTo(null);
        
        btnOK.addActionListener(this);
        btnOK.setActionCommand("ok");
        
        btnCancel.addActionListener(this);
        btnCancel.setActionCommand("cancel");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblPlaca = new javax.swing.JLabel();
        txfPlaca = new javax.swing.JFormattedTextField();

        setTitle("Saída de Veículo");
        setResizable(false);

        jPanel1.setMinimumSize(new java.awt.Dimension(400, 200));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 200));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnOK.setText("OK");
        jPanel1.add(btnOK, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, -1, -1));

        btnCancel.setText("Cancelar");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 130, -1, -1));

        lblPlaca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPlaca.setText("Placa:");
        jPanel1.add(lblPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 40, 20));

        txfPlaca.setColumns(15);
        try {
            txfPlaca.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("UUU#A##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txfPlaca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfPlacaActionPerformed(evt);
            }
        });
        jPanel1.add(txfPlaca, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txfPlacaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfPlacaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfPlacaActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblPlaca;
    private javax.swing.JFormattedTextField txfPlaca;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        String cmd = e.getActionCommand();
        if(cmd.equals("ok")){
            EstacionamentoController controller = new EstacionamentoController();
            // controller processa a saída
            Movimentacao movimentacao = null;
            try {
                movimentacao = controller.processarSaida(txfPlaca.getText());
            } catch (VeiculoException | EstacionamentoException ex) {
                JOptionPane.showMessageDialog(null, ex.getMessage(), "Falha na Saída", JOptionPane.ERROR_MESSAGE);
            }
            TelaResumoPagamento telaResumo = new TelaResumoPagamento(movimentacao, parent);
            telaResumo.setVisible(true);
        }
        else if(cmd.equals("cancel")){
            parent.setVisible(true);
        }
        this.dispose();
    }
}
