/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apresentacao;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class TelaLogin extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        setResizable(false);
        initComponents();
        setLocationRelativeTo(null);
        jPanel4.setVisible(false);
        rdbOperacional.addActionListener(this);
        rdbOperacional.setActionCommand("operacional");
        rdbRelatorio.addActionListener(this);
        rdbRelatorio.setActionCommand("relatorio");
        
        btnOK.addActionListener(this);
        btnOK.setActionCommand("ok");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        rdbOperacional = new javax.swing.JRadioButton();
        rdbRelatorio = new javax.swing.JRadioButton();

        buttonGroup1.add(rdbOperacional);
        buttonGroup1.add(rdbRelatorio);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);

        jPanel1.setLayout(new java.awt.BorderLayout());

        btnOK.setText("OK");
        jPanel2.add(btnOK);

        jPanel1.add(jPanel2, java.awt.BorderLayout.SOUTH);

        jPanel3.setLayout(new java.awt.BorderLayout());

        lblSenha.setText("Senha:");
        jPanel4.add(lblSenha);

        txtSenha.setColumns(20);
        jPanel4.add(txtSenha);

        jPanel3.add(jPanel4, java.awt.BorderLayout.SOUTH);

        rdbOperacional.setSelected(true);
        rdbOperacional.setText("Operacional");
        rdbOperacional.setToolTipText("");
        jPanel5.add(rdbOperacional);

        rdbRelatorio.setText("Relatório");
        jPanel5.add(rdbRelatorio);

        jPanel3.add(jPanel5, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        JFrame tela = null;
        if (e.getActionCommand().equals("operacional")){
            jPanel4.setVisible(false);
        }
        else if (e.getActionCommand().equals("relatorio")){
            jPanel4.setVisible(true);
            txtSenha.setText("");
        }
        
        else if (e.getActionCommand().equals("ok")){
            if (rdbOperacional.isSelected()){
                tela = new TelaInicialMovimentacao();
                tela.setVisible(true);
            }
            else{
                String senha = new String(txtSenha.getPassword());
                if (senha.equals("impacta")){
                    tela = new TelaInicialRelatorio();
                    tela.setVisible(true);
                }
                else {
                    JOptionPane.showMessageDialog(null, "Senha Inválida", "Falha Login", JOptionPane.ERROR_MESSAGE);
                    return;
                }
            }
            this.dispose();
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JRadioButton rdbOperacional;
    private javax.swing.JRadioButton rdbRelatorio;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
